# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlipNumberViewExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlipNumberViewExample
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']

end
